### ISSUE TITLE
about PR 1..

### ISSUE THREAD

**Issue by clojj** [atom/tree-sitter-syntax#9]
https://github.com/atom-archive/tree-sitter-syntax/pull/1

this PR is a very nice idea!

is this repo (tree-sitter-syntax) obsolete (that is "language-..." repos are responsible for adding tree-sitter languages) ?

it should be worthwhile getting this PR into a "language-..." package
where would "tree-sitter-decoration-layer.js" live in the atom/atom-packages ?

**Comment by lee-dohm** [comment]
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
